// Generated by CoffeeScript 1.10.0
var Component, type;

type = Component("ChannelBar");

type.contextType = require(".");

type.propTypes = {};

type.render(function() {
  var foo;
  return foo = View({
    style: this.styles.foo()
  });
});

type.styles = {
  foo: function() {
    return {
      position: "absolute",
      backgroundColor: this.bkgColor
    };
  },
  bar: {
    position: "absolute"
  }
};

module.exports = Component = NamedFunction("Component", function() {});

Component.Builder = require("./ComponentBuilder");
