// Generated by CoffeeScript 1.12.4
var Builder, OneOf, Property, Type, ValidationMixin, Validator, assertType, isDev, isType, noKind, prototype, sync, targets;

assertType = require("assertType");

Validator = require("Validator");

Property = require("Property");

Builder = require("Builder");

isType = require("isType");

OneOf = require("OneOf");

isDev = require("isDev");

sync = require("sync");

Type = require("./Type");

Type.Builder = require("./TypeBuilder");

Type.Mixin = Builder.Mixin;

module.exports = Type;

prototype = Type.Builder.prototype;

Type.extend = function(key, method) {
  assertType(key, String);
  assertType(method, Function);
  if (prototype[key]) {
    throw Error("'" + key + "' already exists");
  }
  prototype[key] = method;
};

targets = [Type.prototype, Validator.prototype, Function, Object, Array, String, Boolean, Number, RegExp, Date, Error, Symbol];

noKind = OneOf([Array, String, Boolean, Number, RegExp, Date, Symbol]);

ValidationMixin = require("./ValidationMixin");

sync.each(ValidationMixin, function(config, key) {
  var i, j, len, len1, prop, target;
  prop = isType(config, Object) ? Property(config) : Property({
    value: config
  });
  isDev && (prop.hidden = true);
  if (key === "Kind") {
    for (i = 0, len = targets.length; i < len; i++) {
      target = targets[i];
      if (!noKind.test(target)) {
        prop.define(target, key);
      }
    }
    return;
  }
  for (j = 0, len1 = targets.length; j < len1; j++) {
    target = targets[j];
    prop.define(target, key);
  }
});
