// Generated by CoffeeScript 1.12.4
var Arguments, Builder, Either, NamedFunction, TypeBuilder, assertType, createArguments, define, emptyFunction, frozen, isDev, isType, setKind, setType, sliceArray;

frozen = require("Property").frozen;

NamedFunction = require("NamedFunction");

emptyFunction = require("emptyFunction");

assertType = require("assertType");

sliceArray = require("sliceArray");

Arguments = require("Arguments");

Builder = require("Builder");

setKind = require("setKind");

setType = require("setType");

Either = require("Either");

isType = require("isType");

define = require("define");

isDev = require("isDev");

TypeBuilder = NamedFunction("TypeBuilder", function(name) {
  var self;
  self = Builder(name);
  return setType(self, TypeBuilder);
});

module.exports = setKind(TypeBuilder, Builder);

define(TypeBuilder.prototype, {
  createArgs: function(callback) {
    this._phases.push("args", callback);
  },
  defineArgs: function(config) {
    var args;
    if (this._args) {
      throw Error("Cannot call 'defineArgs' more than once!");
    }
    assertType(config, Either(Function, Object, Array));
    args = isType(config, Function) ? createArguments(config()) : Arguments(config);
    frozen.define(this, "_args", {
      value: args
    });
    if (!args.isArray) {
      this.defineStatics({
        optionTypes: {
          value: args.types
        }
      });
    }
    this._phases.push("args", function(values) {
      var error;
      values = args.initialize(values);
      if (isDev) {
        error = args.validate(values);
        if (error) {
          throw error;
        }
      }
      if (args.isArray) {
        return values;
      }
      return [values];
    });
  }
});

define(TypeBuilder.prototype, {
  __createArgBuilder: function() {
    var buildArgs, callbacks;
    if (!this._phases.has("args")) {
      return emptyFunction.thatReturnsArgument;
    }
    callbacks = this._phases.get("args");
    return buildArgs = function(args, context) {
      var callback, i, len;
      args = sliceArray(args);
      for (i = 0, len = callbacks.length; i < len; i++) {
        callback = callbacks[i];
        args = callback.call(context, args);
      }
      return args;
    };
  }
});

createArguments = function(config) {
  var args, key, value;
  assertType(config, Object);
  args = Arguments.Builder();
  if (config.types == null) {
    config.types = isType(config.defaults, Object) ? {} : [];
  }
  for (key in config) {
    value = config[key];
    (value != null) && args.set(key, value);
  }
  return args.build();
};
