// Generated by CoffeeScript 1.11.1
var Kind, Maybe, Typle, cloneArgs, mutable;

mutable = require("Property").mutable;

cloneArgs = require("cloneArgs");

Typle = require("Typle");

Maybe = require("Maybe");

Kind = require("Kind");

module.exports = {
  isRequired: {
    get: function() {
      return {
        type: this,
        required: true
      };
    }
  },
  withDefault: function(value) {
    return {
      type: this,
      "default": value
    };
  },
  or: function() {
    var types;
    types = cloneArgs(arguments);
    types.unshift(this);
    return Typle(types);
  },
  Maybe: {
    get: function() {
      var value;
      value = Maybe(this);
      mutable.define(this, "Maybe", {
        get: function() {
          return value;
        },
        enumerable: false
      });
      return value;
    }
  },
  Kind: {
    get: function() {
      var value;
      value = Kind(this);
      mutable.define(this, "Kind", {
        get: function() {
          return value;
        },
        enumerable: false
      });
      return value;
    }
  }
};
